---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: elastic_01
    image: docker.io/pycontribs/centos:8
    pre_build_image: false  # true

provisioner:
  name: ansible
verifier:
  name: ansible
