---
# tasks file for logstash
  - name: Upload tar.gz logstash from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      mode: 0755
      # timeout: 60
      # force: true
      # validate_certs: false
    register: get_logstash
    until: get_logstash is succeeded
    tags: logstash

  - name: Create directrory for logstash ({{ logstash_home }})
    file:
      path: "{{ logstash_home }}"
      state: directory
    tags: logstash

  - name: Extract logstash in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      dest: "{{ logstash_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ logstash_home }}/bin/logstash"
    tags:
      - skip_ansible_lint
      - logstash

  - name: Set environment logstash
    become: true
    template:
      src: templates/logstash.sh.j2
      dest: /etc/profile.d/logstash.sh
    tags: logstash