---
- src: https://github.com/ozaryx/java-role.git
  scm: git
  version: "1.0.1"
  name: java

- src: https://github.com/ozaryx/elastic-role.git
  scm: git
  version: "1.0.1"
  name: elastic

- src: https://github.com/ozaryx/kibana-role.git
  scm: git
  version: "1.0.1"
  name: kibana

- src: https://github.com/ozaryx/logstash-role.git
  scm: git
  version: "1.0.1"
  name: logstash
