---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kibana_01
    image: docker.io/pycontribs/centos:8
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
